In [46]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/tmdb-movie-metadata/tmdb_5000_movies.csv
/kaggle/input/tmdb-movie-metadata/tmdb_5000_credits.csv

In [47]:
# Load the TMDB movie metadata and credits datasets into Pandas DataFrames for analysis.
movies = pd.read_csv('/kaggle/input/tmdb-movie-metadata/tmdb_5000_movies.csv')
credits = pd.read_csv('/kaggle/input/tmdb-movie-metadata/tmdb_5000_credits.csv')

In [48]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [49]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [50]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [51]:
# Merges the movies and credits DataFrames on the title column to combine movie details with corresponding credits.
movies = movies.merge(credits,on='title')

In [52]:
movies['original_language'].value_counts()

original_language
en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ro       2
id       2
ar       2
vi       1
sl       1
ps       1
no       1
ky       1
hu       1
pl       1
af       1
nb       1
tr       1
is       1
xx       1
te       1
el       1
Name: count, dtype: int64

In [53]:
# after initial data exploration, following are the columns that have most impact on recommendation,
# hence dropping other columns
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [54]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

**Data Preprocessing**

Now we will combine the terms in overview, genres,keywords, cast columns into a single column using string manupulation methods

In [55]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

In [56]:
# dropping the null values
movies.dropna(inplace=True)
movies.isna().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [57]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [58]:
movies['genres'].dtype

dtype('O')

In [59]:
# Parse the string representation of movie's genres into a Python list of dictionaries using ast.literal_eval.
import ast
ast.literal_eval(movies['genres'].iloc[0])

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [60]:
# function to extract genre names into a list
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [61]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [62]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [63]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [64]:
# slice the cast names to keep only the names of 3 lead actors
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

In [65]:
# function to extract teh director's name from the cast column
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [66]:
movies['crew'] = movies['crew'].apply(fetch_director)
movies.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
1471,2162,Chill Factor,A store clerk and an ice cream truck driver ar...,"[Action, Comedy, Thriller]",[],"[Cuba Gooding Jr., Skeet Ulrich, Peter Firth]",[Hugh Johnson]
2129,1649,Bill & Ted's Bogus Journey,Amiable slackers Bill and Ted are once again r...,"[Adventure, Comedy, Family, Fantasy, Science F...","[future, dying and death, heaven, time travel,...","[Keanu Reeves, Alex Winter, George Carlin]",[Peter Hewitt]
1581,59436,Midnight in Paris,A romantic comedy about a family traveling to ...,"[Fantasy, Comedy, Romance]","[paris, painter, detective, based on novel, sc...","[Owen Wilson, Rachel McAdams, Kurt Fuller]",[Woody Allen]
4020,468,My Own Private Idaho,"In this loose adaptation of Shakespeare's ""Hen...","[Drama, Romance]","[individual, gay, father son relationship, rom...","[River Phoenix, Keanu Reeves, James Russo]",[Gus Van Sant]
1366,51540,Horrible Bosses,"For Nick, Kurt and Dale, the only thing that w...","[Comedy, Crime]","[conspiracy of murder, bad boss, employee, dea...","[Jennifer Aniston, Jason Bateman, Charlie Day]",[Seth Gordon]

In [67]:
# in order to remove whitespaces so as to avoid confusion between different people with same name

def collapse(L):
    return [i.replace(" ", "") for i in L]

In [68]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [69]:
# Split each movie overview into a list of words using whitespace as the delimiter.
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [70]:
# Create a new column 'tags' by concatenating the 'overview', 'genres', 'keywords', 'cast', and 'crew' columns for each movie.
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [71]:
# Drops the columns 'overview', 'genres', 'keywords', 'cast', and 'crew' from the movies DataFrame, keeping only the remaining relevant data.
new = movies.drop(columns=['overview','genres','keywords','cast','crew'])

In [72]:
# Convert the list of words in the 'tags' column into a single string by joining the words with a space
new['tags'] = new['tags'].apply(lambda x: " ".join(x))
new.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [73]:
new.iloc[0].tags

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [74]:
# vectorization of each tag
# bag of words techinique

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=8000,stop_words='english')
    
vector = cv.fit_transform(new['tags']).toarray()
vector.shape

(4806, 8000)

In [75]:
vector[0]

array([0, 0, 0, ..., 0, 0, 0])

In [76]:
# Return the list of the feature names (vocabulary) generated by the CountVectorizer (cv) after fitting it to the data.
cv.get_feature_names_out().tolist()

['000',
 '007',
 '10',
 '100',
 '10th',
 '11',
 '12',
 '12th',
 '13',
 '14',
 '15',
 '150',
 '15th',
 '16',
 '16th',
 '17',
 '17th',
 '18',
 '1863',
 '1890',
 '18th',
 '18thcentury',
 '19',
 '1910',
 '1910s',
 '1920',
 '1920s',
 '1927',
 '1930s',
 '1937',
 '1940s',
 '1941',
 '1944',
 '1945',
 '1950',
 '1950s',
 '1955',
 '1959',
 '1960',
 '1960s',
 '1962',
 '1964',
 '1965',
 '1967',
 '1969',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1976',
 '1977',
 '1979',
 '1980',
 '1980s',
 '1984',
 '1985',
 '1986',
 '1987',
 '1990',
 '1990s',
 '1994',
 '1995',
 '1996',
 '1997',
 '1999',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2007',
 '2008',
 '2009',
 '2011',
 '2012',
 '20th',
 '21st',
 '21stcentury',
 '22nd',
 '23',
 '24',
 '25',
 '27',
 '30',
 '300',
 '35',
 '3d',
 '40',
 '47',
 '50',
 '500',
 '51',
 '60',
 '60s',
 '70',
 '70s',
 '7th',
 'aaron',
 'aaroneckhart',
 'aaronseltzer',
 'aarontaylor',
 'abandoned',
 'abandons',
 'abby',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abortion',
 'abrams',
 'abroad',
 'absence',
 'abuse',
 'abused',
 'abusive',
 'academic',
 'academy',
 'accept',
 'acceptance',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'acclaimed',
 'accompanied',
 'accomplish',
 'accomplished',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'ad',
 'ada',
 'adam',
 'adammckay',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'add',
 'addict',
 'addicted',
 'addiction',
 'addition',
 'addled',
 'adds',
 'adjust',
 'admiral',
 'admits',
 'adolescence',
 'adolescent',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adorable',
 'adrenaline',
 'adrienbrody',
 'adrift',
 'adult',
 'adultanimation',
 'adultery',
 'adulthood',
 'adults',
 'advanced',
 'advancement',
 'advantage',
 'adventure',
 'adventurer',
 'adventures',
 'adventurous',
 'advertisement',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affect',
 'affected',
 'affection',
 'affections',
 'affluent',
 'afford',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'afternoon',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'ages',
 'aggressionbyanimal',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aidanquinn',
 'aided',
 'aids',
 'ailing',
 'aim',
 'air',
 'airborne',
 'aircraft',
 'airplane',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alanarkin',
 'alaska',
 'alaskan',
 'albert',
 'albertbrooks',
 'albertfinney',
 'alcatraz',
 'alcohol',
 'alcoholabuse',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alejandrogonzáleziñárritu',
 'alex',
 'alexander',
 'alexanderpayne',
 'alexanderskarsgård',
 'alexapenavega',
 'alexia',
 'alexisbledel',
 'alexkendrick',
 'alexpettyfer',
 'alexproyas',
 'alfie',
 'alfonsocuarón',
 'alfredhitchcock',
 'alfredmolina',
 'algeria',
 'ali',
 'alice',
 'alicebraga',
 'aliciasilverstone',
 'aliciawitt',
 'alien',
 'alienated',
 'alienation',
 'aliencontact',
 'alieninfection',
 'alieninvasion',
 'alienlife',
 'alienplanet',
 'aliens',
 'alike',
 'alilarter',
 'alive',
 'allegedly',
 'allen',
 'allenhughes',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allowed',
 'allowing',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alpha',
 'alps',
 'alter',
 'altered',
 'altering',
 'alternate',
 'alternatedimension',
 'alternatehistory',
 'alternatereality',
 'alternative',
 'alvin',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandabynes',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'amazon',
 'ambassador',
 'amber',
 'amberheard',
 'ambertamblyn',
 'ambition',
 'ambitions',
 'ambitious',
 'ambulance',
 'ambush',
 'ambushed',
 'amelia',
 'america',
 'americaferrera',
 'american',
 'americanabroad',
 'americancivilwar',
 'americandream',
 'americanfootball',
 'americanfootballplayer',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amusement',
 'amusementpark',
 'amusing',
 'amy',
 'amyadams',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientgreece',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrew',
 'andrewadamson',
 'andrewgarfield',
 'andrewniccol',
 'android',
 'andrzejbartkowiak',
 'andy',
 'andyfickman',
 'andygarcía',
 'andyserkis',
 'andytennant',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'anime',
 'anjelicahuston',
 'ann',
 'anna',
 'annabelle',
 'annafaris',
 'annafriel',
 'annakendrick',
 'annasophiarobb',
 'anne',
 'annefletcher',
 'annehathaway',
 'anneheche',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'announces',
 'annual',
 'anonymity',
 'anonymous',
 'answer',
 'answers',
 'ant',
 'antarctic',
 'antarctica',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthonymackie',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antisemitism',
 'antoinefuqua',
 'anton',
 'antonio',
 'antoniobanderas',
 'antony',
 'antonyelchin',
 'anxiety',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appearance',
 'appearing',
 'appears',
 'apple',
 'appointed',
 'appreciate',
 'apprentice',
 'approach',
 'approached',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'arab',
 'arbitrarylaw',
 'arch',
 'archaeologist',
 'archeology',
 'archer',
 'archery',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'arizona',
 'arm',
 'armed',
 'armiehammer',
 'armored',
 'arms',
 'armsdeal',
 'armsdealer',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arranged',
 'arrangedmarriage',
 'arrangement',
 'arranges',
 'array',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrived',
 'arrives',
 'arriving',
 'arrogant',
 'arson',
 'art',
 'artgallery',
 'arthur',
 'article',
 'artifact',
 'artificial',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ash',
 'ashes',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'asian',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspects',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assist',
 'assistance',
 'assistant',
 'assortment',
 'assume',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'atheist',
 'athlete',
 'athletes',
 'athletic',
 'atlanta',
 'atlantic',
 'atomegoyan',
 'atomic',
 'atomicbomb',
 'attack',
 'attacked',
 'attacking',
 'attacks',
 'attempt',
 'attempted',
 'attemptedmurder',
 'attempting',
 'attempts',
 'attempttoescape',
 'attend',
 'attendant',
 'attending',
 'attends',
 'attention',
 'attic',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'auction',
 'audience',
 'audiences',
 'audition',
 'audreytautou',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'austria',
 'austrian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'autobiographical',
 'automobileracing',
 'available',
 'avenge',
 'average',
 'avoid',
 'avoiding',
 'await',
 'awaits',
 'awake',
 'awakens',
 'award',
 'awards',
 'away',
 'awesome',
 'awkward',
 'awry',
 'ax',
 'axe',
 'axel',
 'babe',
 'babies',
 'baby',
 'babysitter',
 'bachelor',
 'backdrop',
 'backed',
 'background',
 'backgrounds',
 'backpacker',
 'backstage',
 'backwater',
 'backyard',
 'bad',
 'badly',
 'badmother',
 'bag',
 'bahamas',
 'bail',
 'bailey',
 'baker',
 'balance',
 'ball',
 'ballet',
 'balloon',
 'baltimore',
 'band',
 'bandit',
 'bandits',
 'bands',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'banking',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barbara',
 'barbarian',
 'barbershop',
 'barbrastreisand',
 'barely',
 'bargained',
 'barn',
 'barnes',
 'barney',
 'baron',
 'barriers',
 'barry',
 'barrylevinson',
 'barrypepper',
 'barrysonnenfeld',
 'bars',
 'base',
 'baseball',
 'based',
 'basedonchildren',
 'basedoncomicbook',
 'basedonfilm',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basis',
 'basketball',
 'bathtub',
 'batman',
 'battalion',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'beard',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beaten',
 'beating',
 'beats',
 'beau',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becky',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'beguilement',
 'behavior',
 'beheading',
 'beijing',
 'beings',
 'belgium',
 'belief',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'bell',
 'bella',
 'bellas',
 'belong',
 'belongs',
 'beloved',
 'belt',
 'ben',
 'benaffleck',
 'benchaplin',
 'bending',
 'beneath',
 'benedictcumberbatch',
 'benefit',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennet',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'bernie',
 'berniemac',
 'best',
 'bestfriend',
 'bestfriendsinlove',
 'bet',
 'beth',
 'bethany',
 'betrayal',
 'betrayed',
 'bets',
 'bettemidler',
 'better',
 'betty',
 'bettythomas',
 'beverly',
 'bible',
 'biblical',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bigotry',
 'bike',
 'biker',
 'bikers',
 'bikini',
 'bilbo',
 'billcondon',
 'billewoodruff',
 'billhader',
 'billion',
 'billionaire',
 'billmoseley',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billyconnolly',
 'billycrudup',
 'billycrystal',
 'biographical',
 'biography',
 'biopic',
 'bird',
 'birdee',
 'birth',
 'birthday',
 'bisexual',
 'bisexuality',
 'bishop',
 'bit',
 'bite',
 'bitten',
 'bitter',
 'bittersweet',
 'bizarre',
 'black',
 'blackandwhite',
 'blackhole',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blacksmith',
 'blade',
 'blake',
 'blame',
 'blart',
 'blast',
 'blaxploitation',
 'blind',
 'blinddate',
 'blindness',
 'blindnessandimpairedvision',
 'bliss',
 'blizzard',
 'block',
 'blockbuster',
 'blofeld',
 'blog',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'bloom',
 'blossoms',
 'blow',
 'blowjob',
 'blown',
 'blows',
 'blu',
 'blue',
 'blues',
 'blunt',
 'bly',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'boatchase',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobclark',
 'bobgunton',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bodyhorror',
 'bohemian',
 'bold',
 'bollywood',
 'bolt',
 'bomb',
 'bomber',
 'bombing',
 'bond',
 'bondage',
 'bonds',
 'bone',
 'bones',
 'bonniehunt',
 'boo',
 'booby',
 'boobytrap',
 'book',
 'booked',
 'books',
 'boost',
 'boots',
 'booze',
 'border',
 'borders',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'bourne',
 'bout',
 'bowling',
 'box',
 'boxer',
 'boxers',
 'boxing',
 'boxingmatch',
 'boy',
 'boyd',
 'boyfriend',
 'boys',
 'brad',
 'bradanderson',
 'bradbird',
 'bradleycooper',
 'bradpitt',
 'brain',
 'braintumor',
 'brainwashing',
 'brand',
 'brandon',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breakingthefourthwall',
 'breaks',
 'breakup',
 'breast',
 'breathing',
 'breeding',
 'brendan',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brentspiner',
 'brettratner',
 'brewing',
 'brian',
 'briancox',
 'briandepalma',
 'brianhelgeland',
 'brianlevant',
 'brianrobbins',
 'bride',
 'bridesmaid',
 'bridge',
 'bridgetfonda',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britisharmy',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronson',
 'bronx',
 'brood',
 'brooklyn',
 'brooklynnewyorkcity',
 'brooks',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brotherhood',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucecampbell',
 'brucedern',
 'brucegreenwood',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryancranston',
 'bryansinger',
 'brycedallashoward',
 'buck',
 'bud',
 'budapest',
 'buddies',
 'buddy',
 'buddycomedy',
 'buddycop',
 ...]

In [77]:
# Import the nltk library and initialize the PorterStemmer object (ps) for stemming words to their root form using the Porter stemming algorithm.
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [78]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [79]:
stem(new.iloc[0].tags)

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [80]:
new['tags'] = new['tags'].apply(stem)

In [81]:

vector = cv.fit_transform(new['tags']).toarray()
vector.shape

(4806, 8000)

In [82]:
cv.get_feature_names_out().tolist()

['000',
 '007',
 '10',
 '100',
 '10th',
 '11',
 '12',
 '12th',
 '13',
 '14',
 '15',
 '150',
 '15th',
 '16',
 '16th',
 '17',
 '17th',
 '18',
 '1863',
 '1890',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1927',
 '1930',
 '1930s',
 '1937',
 '1940',
 '1940s',
 '1941',
 '1944',
 '1945',
 '1950',
 '1950s',
 '1955',
 '1959',
 '1960',
 '1960s',
 '1962',
 '1964',
 '1965',
 '1967',
 '1969',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1976',
 '1977',
 '1979',
 '1980',
 '1980s',
 '1984',
 '1985',
 '1986',
 '1987',
 '1990',
 '1994',
 '1995',
 '1996',
 '1997',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2007',
 '2008',
 '2009',
 '2011',
 '2012',
 '20th',
 '21st',
 '21stcenturi',
 '22nd',
 '23',
 '24',
 '25',
 '27',
 '28',
 '29',
 '30',
 '300',
 '35',
 '3d',
 '40',
 '400',
 '47',
 '50',
 '500',
 '51',
 '60',
 '60s',
 '70',
 '7th',
 '80',
 'aaron',
 'aaroneckhart',
 'aaronseltz',
 'aarontaylor',
 'abandon',
 'abbi',
 'abbiecornish',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'aborigin',
 'abort',
 'abov',
 'abram',
 'abroad',
 'absolut',
 'absurd',
 'abus',
 'abuse',
 'academ',
 'academi',
 'academy',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acid',
 'acquaint',
 'acquir',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'ada',
 'adam',
 'adambrodi',
 'adamgarcia',
 'adammckay',
 'adams',
 'adamsandl',
 'adamscott',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'addiction',
 'addit',
 'addl',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adolf',
 'adolfhitl',
 'adopt',
 'adoptivefath',
 'ador',
 'adrian',
 'adrianlyn',
 'adrienbrodi',
 'adrift',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'adults',
 'advanc',
 'advantag',
 'advantage',
 'adventur',
 'adventure',
 'adventures',
 'adversari',
 'advertis',
 'advic',
 'advice',
 'advis',
 'affair',
 'affect',
 'affection',
 'afflict',
 'affluent',
 'afford',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'africanamerican',
 'afro',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'afternoon',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'aggressionbyanim',
 'ago',
 'agre',
 'agrees',
 'ahead',
 'aid',
 'aidan',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airborn',
 'aircraft',
 'airforc',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alanarkin',
 'alaska',
 'alaskan',
 'albert',
 'albertbrook',
 'albertfinney',
 'alcatraz',
 'alcohol',
 'alcoholabus',
 'alecbaldwin',
 'alejandrogonzáleziñárritu',
 'alex',
 'alexanderpayn',
 'alexanderskarsgård',
 'alexandradaddario',
 'alexandreaja',
 'alexapenavega',
 'alexia',
 'alexisbledel',
 'alexkendrick',
 'alexpettyf',
 'alexproya',
 'alfi',
 'alfonsocuarón',
 'alfredhitchcock',
 'alfredmolina',
 'algeria',
 'ali',
 'alic',
 'alice',
 'alicebraga',
 'aliciasilverston',
 'aliciawitt',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'alike',
 'alilart',
 'aliv',
 'alive',
 'alleg',
 'allegedli',
 'allen',
 'alli',
 'allianc',
 'allies',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alt',
 'alter',
 'altern',
 'alternatehistori',
 'alternater',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandabyn',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'amber',
 'amberheard',
 'ambertamblyn',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'amelia',
 'america',
 'americaferrera',
 'american',
 'americanabroad',
 'americancivilwar',
 'americandream',
 'americanfootbal',
 'americanfootballplay',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'amor',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientgreec',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'andrewadamson',
 'andrewgarfield',
 'andrewniccol',
 'andrewstanton',
 'android',
 'andrzejbartkowiak',
 'andy',
 'andyfickman',
 'andygarcía',
 'andysamberg',
 'andyserki',
 'andytenn',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annabel',
 'annafari',
 'annafriel',
 'annakendrick',
 'annasophiarobb',
 'anne',
 'annebancroft',
 'annefletch',
 'annehathaway',
 'annehech',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annoy',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'answers',
 'ant',
 'antarct',
 'antarctica',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antisemit',
 'antiterror',
 'antoinefuqua',
 'anton',
 'antonio',
 'antoniobandera',
 'antonyelchin',
 'anxieti',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'apollo',
 'apostl',
 'appalachia',
 'appar',
 'appear',
 'appears',
 'appl',
 'apple',
 'appli',
 'appoint',
 'appreci',
 'apprehend',
 'apprentic',
 'approach',
 'approaches',
 'april',
 'aquarium',
 'arab',
 'arabian',
 'arbitrarylaw',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'archeri',
 'architect',
 'archiv',
 'arctic',
 'arduou',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arizona',
 'arm',
 'armageddon',
 'armandassant',
 'armi',
 'armiehamm',
 'arminmueller',
 'armor',
 'armsdeal',
 'armstrong',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'array',
 'arrest',
 'arrested',
 'arriv',
 'arrive',
 'arrives',
 'arrog',
 'arson',
 'art',
 'artgalleri',
 'arthur',
 'articl',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'artists',
 'arts',
 'artthief',
 'asabutterfield',
 'asgard',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashleytisdal',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'asleep',
 'aspect',
 'asperger',
 'aspir',
 'aspirations',
 'ass',
 'assassin',
 'assassination',
 'assassins',
 'assault',
 'assaultrifl',
 'assembl',
 'assign',
 'assignment',
 'assist',
 'assistant',
 'associ',
 'assort',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atlant',
 'atlanta',
 'atlanticocean',
 'atom',
 'atomegoyan',
 'atomicbomb',
 'atroc',
 'attach',
 'attack',
 'attacks',
 'attempt',
 'attemptedmurd',
 'attempttoescap',
 'attend',
 'attent',
 'attention',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'audrey',
 'audreytaut',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'austria',
 'austrian',
 'author',
 'authorities',
 'authority',
 'autism',
 'autist',
 'auto',
 'autobiograph',
 'automaton',
 'automobilerac',
 'avail',
 'aveng',
 'averag',
 'avert',
 'aviat',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awe',
 'awesom',
 'awkward',
 'awri',
 'awry',
 'ax',
 'axe',
 'axel',
 'babe',
 'babi',
 'baby',
 'babysitt',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'backstag',
 'backwat',
 'backyard',
 'bad',
 'badli',
 'bag',
 'bahama',
 'bail',
 'bailey',
 'baker',
 'balanc',
 'balance',
 'balboa',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bannon',
 'bar',
 'barbara',
 'barbarian',
 'barbershop',
 'barbrastreisand',
 'barcelonaspain',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barricad',
 'barrier',
 'barrio',
 'barry',
 'barrylevinson',
 'barrypepp',
 'barrysonnenfeld',
 'bars',
 'bart',
 'bas',
 'base',
 'basebal',
 'baseball',
 'basedonarticl',
 'basedoncartoon',
 'basedonchildren',
 'basedoncomicbook',
 'basedonfairytal',
 'basedonfilm',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonshortstori',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basket',
 'basketbal',
 'basketball',
 'bat',
 'bathroom',
 'bathtub',
 'batman',
 'battalion',
 'battl',
 'battle',
 'battleassign',
 'battlefield',
 'baxter',
 'bay',
 'bazluhrmann',
 'bdsm',
 'beach',
 'beachhous',
 'beam',
 'bear',
 'beard',
 'beast',
 'beasts',
 'beat',
 'beaten',
 'beau',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becca',
 'becki',
 'beckon',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'beethoven',
 'befor',
 'befriend',
 'beg',
 'began',
 'beggar',
 'begin',
 'begins',
 'beguil',
 'behavior',
 'behead',
 'belgium',
 'belief',
 'beliefs',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'beloved',
 'belt',
 'ben',
 'benaffleck',
 'benchaplin',
 'bend',
 'beneath',
 'benedictcumberbatch',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennet',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'berni',
 'berniemac',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'bethani',
 'betray',
 'betrayal',
 'betroth',
 'bettemidl',
 'better',
 'betti',
 'bettythoma',
 'beverli',
 'beverlyhil',
 'bia',
 'bianca',
 'bibl',
 'biblic',
 'bicker',
 'bicycl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bigotri',
 'bike',
 'biker',
 'bikini',
 'bilbo',
 'billcondon',
 'billewoodruff',
 'billhad',
 'billi',
 'billion',
 'billionair',
 'billmoseley',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billyconnolli',
 'billycrudup',
 'billycryst',
 'billywild',
 'bind',
 'binocular',
 'bio',
 'biograph',
 'biographi',
 'biolog',
 'biologicalweapon',
 'biologist',
 'biopic',
 'bird',
 'birde',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitten',
 'bitter',
 'bittersweet',
 'bizarr',
 'black',
 'blackandwhit',
 'blackhol',
 'blackmag',
 'blackmail',
 'blackout',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blake',
 'blakel',
 'blame',
 'blart',
 'blast',
 'blaxploit',
 'blaze',
 'bleek',
 'blend',
 'bless',
 'blind',
 'blinddat',
 'blindnessandimpairedvis',
 'bliss',
 'blizzard',
 'block',
 'blockbust',
 'blofeld',
 'blog',
 'blond',
 'blonde',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'bloom',
 'blossom',
 'blow',
 'blowjob',
 'blown',
 'blu',
 'blue',
 'blunt',
 'blur',
 'bly',
 'board',
 'boardingschool',
 'boat',
 'boatchas',
 'bob',
 'bobbi',
 'bobby',
 'bobbyfarrelli',
 'bobclark',
 'bobgunton',
 'bobhoskin',
 'bodi',
 'bodies',
 'body',
 'bodyguard',
 'bodyhorror',
 'bohemian',
 'bold',
 'bollywood',
 'bolt',
 'bomb',
 'bomber',
 'bond',
 'bondag',
 'bone',
 'bonniehunt',
 'boo',
 'boobytrap',
 'book',
 'books',
 'boost',
 'boot',
 'boots',
 'booze',
 'border',
 'bore',
 'boredom',
 'boring',
 'born',
 'borrow',
 'boss',
 'boston',
 'botch',
 'bottl',
 'bounc',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bourn',
 'bout',
 'bowl',
 'box',
 'boxer',
 'boxingmatch',
 'boy',
 'boyd',
 'boyfriend',
 'boys',
 'brad',
 'bradanderson',
 'bradbird',
 'braddourif',
 'bradleycoop',
 'bradpitt',
 'bradsilberl',
 'brain',
 'braintumor',
 'brainwash',
 'branch',
 'brand',
 'brandi',
 'brandon',
 'brash',
 'brass',
 'brave',
 'braveri',
 'brawl',
 'brazil',
 'brazilian',
 'break',
 'breakdanc',
 'breakdown',
 'breakfast',
 'breakingthefourthwal',
 'breakup',
 'breast',
 'breath',
 'breed',
 'brendan',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brentspin',
 'brettratn',
 'brew',
 'brian',
 'briancox',
 'briandepalma',
 'brianhelgeland',
 'brianlev',
 'brianrobbin',
 'brick',
 'bride',
 'bridesmaid',
 'bridg',
 'bridge',
 'bridgetfonda',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britisharmi',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'brock',
 'broke',
 'broken',
 'broker',
 'bronson',
 'bronx',
 'brood',
 ...]

In [83]:
# Calculate the cosine similarity between the movie vectors, which measures the similarity between the movies based on their 'tags', resulting in a similarity matrix.
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)
similarity

array([[1.        , 0.07352146, 0.07784989, ..., 0.04095301, 0.        ,
        0.        ],
       [0.07352146, 1.        , 0.05723638, ..., 0.02258194, 0.        ,
        0.02478408],
       [0.07784989, 0.05723638, 1.        , ..., 0.0239114 , 0.        ,
        0.        ],
       ...,
       [0.04095301, 0.02258194, 0.0239114 , ..., 1.        , 0.03809697,
        0.04141577],
       [0.        , 0.        , 0.        , ..., 0.03809697, 1.        ,
        0.0836242 ],
       [0.        , 0.02478408, 0.        , ..., 0.04141577, 0.0836242 ,
        1.        ]])

In [85]:
# before arranging the similarity from highest to lowest, we have to retain the information of similarity to each movie 
list(enumerate(similarity[0]))

[(0, 0.9999999999999999),
 (1, 0.07352146220938079),
 (2, 0.07784989441615231),
 (3, 0.06320606175199697),
 (4, 0.16865480854231357),
 (5, 0.09622504486493763),
 (6, 0.03419927840283847),
 (7, 0.13046561461068845),
 (8, 0.051899929610768204),
 (9, 0.08697707640712563),
 (10, 0.08697707640712563),
 (11, 0.0834965721446866),
 (12, 0.07453559924999299),
 (13, 0.03669879217087869),
 (14, 0.11640504929492972),
 (15, 0.05547001962252292),
 (16, 0.07071067811865475),
 (17, 0.12297746456210364),
 (18, 0.08664587415167274),
 (19, 0.07284778196108707),
 (20, 0.05229763603684908),
 (21, 0.09548198320525772),
 (22, 0.05536365323582665),
 (23, 0.07784989441615231),
 (24, 0.04714045207910317),
 (25, 0.04517539514526256),
 (26, 0.1363988678940947),
 (27, 0.16269784336399215),
 (28, 0.09802861627917438),
 (29, 0.05547001962252292),
 (30, 0.06030226891555273),
 (31, 0.13840913308956662),
 (32, 0.0769800358919501),
 (33, 0.08606629658238704),
 (34, 0.0),
 (35, 0.08770580193070293),
 (36, 0.15385544379235033),
 (37, 0.07254762501100118),
 (38, 0.07027283689263066),
 (39, 0.06984302957695783),
 (40, 0.06900655593423542),
 (41, 0.14611900125320157),
 (42, 0.0),
 (43, 0.09960238411119948),
 (44, 0.030429030972509232),
 (45, 0.07284778196108707),
 (46, 0.12598815766974242),
 (47, 0.1769149641447584),
 (48, 0.07634644457518243),
 (49, 0.05113099925649136),
 (50, 0.09428090415820634),
 (51, 0.06506000486323556),
 (52, 0.13333333333333333),
 (53, 0.03786412228313766),
 (54, 0.027681826617913324),
 (55, 0.05791629903507591),
 (56, 0.12171612389003693),
 (57, 0.021081851067789197),
 (58, 0.059761430466719695),
 (59, 0.06429904295605494),
 (60, 0.015801515437999243),
 (61, 0.19720265943665385),
 (62, 0.07231015260621873),
 (63, 0.07231015260621873),
 (64, 0.0267739776300833),
 (65, 0.01698823971458752),
 (66, 0.02047650389446504),
 (67, 0.1414213562373095),
 (68, 0.1107273064716533),
 (69, 0.022866478019001178),
 (70, 0.06900655593423542),
 (71, 0.0659380473395787),
 (72, 0.11935247900657214),
 (73, 0.02868876552746235),
 (74, 0.18428853505018536),
 (75, 0.09200874124564723),
 (76, 0.062017367294604234),
 (77, 0.012926112238824687),
 (78, 0.046004370622823615),
 (79, 0.05590169943749475),
 (80, 0.045643546458763846),
 (81, 0.08856148855400954),
 (82, 0.0659380473395787),
 (83, 0.16228816518671588),
 (84, 0.10397504898200727),
 (85, 0.10434983894999018),
 (86, 0.06388765649999399),
 (87, 0.0967301666813349),
 (88, 0.08304547985373997),
 (89, 0.05132002392796674),
 (90, 0.05443310539518174),
 (91, 0.14704292441876157),
 (92, 0.05383819020581655),
 (93, 0.061429511683395124),
 (94, 0.16329931618554522),
 (95, 0.11846977555181848),
 (96, 0.0659380473395787),
 (97, 0.062017367294604234),
 (98, 0.06666666666666667),
 (99, 0.0219793491131929),
 (100, 0.06216698721602092),
 (101, 0.06741998624632421),
 (102, 0.10927167294163062),
 (103, 0.06978985634536183),
 (104, 0.04774099160262886),
 (105, 0.0894427190999916),
 (106, 0.05423261445466405),
 (107, 0.055048188256318034),
 (108, 0.13046561461068845),
 (109, 0.0573775310549247),
 (110, 0.03948992518393949),
 (111, 0.13333333333333333),
 (112, 0.06984302957695783),
 (113, 0.038814833982638804),
 (114, 0.040572041296678976),
 (115, 0.038814833982638804),
 (116, 0.038814833982638804),
 (117, 0.05039526306789696),
 (118, 0.02966627729933232),
 (119, 0.03914801463431356),
 (120, 0.0),
 (121, 0.09312403943594377),
 (122, 0.10379985922153641),
 (123, 0.09872481295984872),
 (124, 0.05923488777590924),
 (125, 0.06921285402059828),
 (126, 0.10989674556596452),
 (127, 0.13169727955327862),
 (128, 0.0),
 (129, 0.07339758434175737),
 (130, 0.023002185311411807),
 (131, 0.09428090415820634),
 (132, 0.055048188256318034),
 (133, 0.024182541670333724),
 (134, 0.1126872339638022),
 (135, 0.0),
 (136, 0.020286020648339488),
 (137, 0.027103854272724725),
 (138, 0.11640504929492972),
 (139, 0.10327955589886444),
 (140, 0.039840953644479794),
 (141, 0.07905694150420949),
 (142, 0.0716114874039433),
 (143, 0.07572824456627532),
 (144, 0.044946657497549475),
 (145, 0.01744746408634046),
 (146, 0.013551927136362362),
 (147, 0.04901430813958719),
 (148, 0.08164965809277261),
 (149, 0.13957971269072367),
 (150, 0.14301938838683884),
 (151, 0.17888543819998318),
 (152, 0.07453559924999299),
 (153, 0.07076598565790336),
 (154, 0.05536365323582665),
 (155, 0.018349396085439344),
 (156, 0.05383819020581655),
 (157, 0.08606629658238704),
 (158, 0.11180339887498948),
 (159, 0.0573775310549247),
 (160, 0.10650160840378231),
 (161, 0.02868876552746235),
 (162, 0.0298142396999972),
 (163, 0.045466289298031565),
 (164, 0.06819943394704735),
 (165, 0.04216370213557839),
 (166, 0.10647942749999),
 (167, 0.07905694150420949),
 (168, 0.15555555555555556),
 (169, 0.0769800358919501),
 (170, 0.09543305571897803),
 (171, 0.019920476822239897),
 (172, 0.17213259316477408),
 (173, 0.02087414303617165),
 (174, 0.09200874124564723),
 (175, 0.06324555320336758),
 (176, 0.025949964805384102),
 (177, 0.0),
 (178, 0.022222222222222223),
 (179, 0.0596284793999944),
 (180, 0.0187812056606337),
 (181, 0.038814833982638804),
 (182, 0.09872481295984872),
 (183, 0.06320606175199697),
 (184, 0.15555555555555556),
 (185, 0.046004370622823615),
 (186, 0.052342392259021375),
 (187, 0.13483997249264842),
 (188, 0.01744746408634046),
 (189, 0.1),
 (190, 0.06584863977663931),
 (191, 0.04348853820356281),
 (192, 0.04216370213557839),
 (193, 0.07172191381865588),
 (194, 0.0),
 (195, 0.0535479552601666),
 (196, 0.046004370622823615),
 (197, 0.03333333333333333),
 (198, 0.051899929610768204),
 (199, 0.07572824456627532),
 (200, 0.09128709291752769),
 (201, 0.0),
 (202, 0.024845199749997663),
 (203, 0.06984302957695783),
 (204, 0.038814833982638804),
 (205, 0.06216698721602092),
 (206, 0.09860132971832693),
 (207, 0.08697707640712563),
 (208, 0.10886621079036347),
 (209, 0.0596284793999944),
 (210, 0.06741998624632421),
 (211, 0.022222222222222223),
 (212, 0.05923488777590924),
 (213, 0.052704627669472995),
 (214, 0.0),
 (215, 0.06030226891555273),
 (216, 0.05443310539518174),
 (217, 0.0769800358919501),
 (218, 0.03513641844631533),
 (219, 0.08164965809277261),
 (220, 0.15811388300841897),
 (221, 0.04216370213557839),
 (222, 0.06978985634536183),
 (223, 0.09200874124564723),
 (224, 0.04767312946227961),
 (225, 0.04216370213557839),
 (226, 0.025949964805384102),
 (227, 0.07254762501100118),
 (228, 0.09872481295984872),
 (229, 0.09428090415820635),
 (230, 0.08132500607904444),
 (231, 0.0),
 (232, 0.10079052613579392),
 (233, 0.0894427190999916),
 (234, 0.0769800358919501),
 (235, 0.06666666666666667),
 (236, 0.09938079899999065),
 (237, 0.05536365323582665),
 (238, 0.09999999999999999),
 (239, 0.08333333333333334),
 (240, 0.040572041296678976),
 (241, 0.06819943394704735),
 (242, 0.06819943394704735),
 (243, 0.08040302522073697),
 (244, 0.08164965809277261),
 (245, 0.07071067811865475),
 (246, 0.06978985634536183),
 (247, 0.0),
 (248, 0.039840953644479794),
 (249, 0.11694106924093724),
 (250, 0.0),
 (251, 0.036155076303109365),
 (252, 0.018490006540840973),
 (253, 0.0563436169819011),
 (254, 0.05923488777590924),
 (255, 0.0),
 (256, 0.09325048082403138),
 (257, 0.04836508334066745),
 (258, 0.015294382258037451),
 (259, 0.05443310539518174),
 (260, 0.17638342073763938),
 (261, 0.021295885499998),
 (262, 0.09390602830316849),
 (263, 0.08451542547285165),
 (264, 0.0),
 (265, 0.024182541670333724),
 (266, 0.08989331499509895),
 (267, 0.05847053462046862),
 (268, 0.046562019717971886),
 (269, 0.0267739776300833),
 (270, 0.08040302522073697),
 (271, 0.06388765649999399),
 (272, 0.024845199749997663),
 (273, 0.018490006540840973),
 (274, 0.07511265766429255),
 (275, 0.1297498240269205),
 (276, 0.05443310539518174),
 (277, 0.04794633014853841),
 (278, 0.1023825194723252),
 (279, 0.08040302522073697),
 (280, 0.0),
 (281, 0.05822225097395821),
 (282, 0.04020151261036849),
 (283, 0.024507154069793594),
 (284, 0.016666666666666666),
 (285, 0.017329174830334547),
 (286, 0.06885303726590962),
 (287, 0.023281009858985943),
 (288, 0.024507154069793594),
 (289, 0.03419927840283847),
 (290, 0.05536365323582665),
 (291, 0.04216370213557839),
 (292, 0.07905694150420949),
 (293, 0.02556549962824568),
 (294, 0.1297498240269205),
 (295, 0.09548198320525772),
 (296, 0.03513641844631533),
 (297, 0.039840953644479794),
 (298, 0.0),
 (299, 0.052342392259021375),
 (300, 0.14757295747452437),
 (301, 0.08281733249999221),
 (302, 0.06324555320336758),
 (303, 0.023570226039551584),
 (304, 0.058742281404186775),
 (305, 0.17177950029416045),
 (306, 0.07071067811865475),
 (307, 0.09486348995453654),
 (308, 0.060858061945018464),
 (309, 0.05536365323582665),
 (310, 0.027563274353157433),
 (311, 0.13046561461068845),
 (312, 0.0879173964527716),
 (313, 0.05039526306789696),
 (314, 0.0),
 (315, 0.07453559924999299),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.09128709291752769),
 (320, 0.02721655269759087),
 (321, 0.0),
 (322, 0.18856180831641267),
 (323, 0.0267739776300833),
 (324, 0.021744269101781406),
 (325, 0.08304547985373997),
 (326, 0.05039526306789696),
 (327, 0.02387049580131443),
 (328, 0.02387049580131443),
 (329, 0.06984302957695783),
 (330, 0.08989331499509895),
 (331, 0.0769800358919501),
 (332, 0.09312403943594377),
 (333, 0.022222222222222223),
 (334, 0.08432740427115679),
 (335, 0.04095300778893008),
 (336, 0.05847053462046862),
 (337, 0.04020151261036849),
 (338, 0.0),
 (339, 0.0417482860723433),
 (340, 0.04348853820356281),
 (341, 0.0659380473395787),
 (342, 0.14638501094228),
 (343, 0.017213259316477405),
 (344, 0.025949964805384102),
 (345, 0.02047650389446504),
 (346, 0.0),
 (347, 0.0),
 (348, 0.05039526306789696),
 (349, 0.06819943394704735),
 (350, 0.04348853820356281),
 (351, 0.0),
 (352, 0.02519763153394848),
 (353, 0.037267799624996496),
 (354, 0.01957400731715678),
 (355, 0.03354364036177518),
 (356, 0.08164965809277261),
 (357, 0.0),
 (358, 0.0535479552601666),
 (359, 0.05536365323582665),
 (360, 0.018490006540840973),
 (361, 0.06741998624632421),
 (362, 0.08606629658238704),
 (363, 0.0890870806374748),
 (364, 0.021081851067789197),
 (365, 0.06666666666666667),
 (366, 0.04774099160262886),
 (367, 0.0),
 (368, 0.1107273064716533),
 (369, 0.10872134550890704),
 (370, 0.045466289298031565),
 (371, 0.08606629658238706),
 (372, 0.042591770999996),
 (373, 0.1554174680400523),
 (374, 0.03091592638401122),
 (375, 0.05547001962252292),
 (376, 0.040572041296678976),
 (377, 0.0),
 (378, 0.0),
 (379, 0.04406526492392318),
 (380, 0.045466289298031565),
 (381, 0.07231015260621873),
 (382, 0.0),
 (383, 0.037267799624996496),
 (384, 0.024845199749997663),
 (385, 0.0),
 (386, 0.0187812056606337),
 (387, 0.021081851067789197),
 (388, 0.0),
 (389, 0.0803219328902499),
 (390, 0.023570226039551584),
 (391, 0.05096471914376256),
 (392, 0.027681826617913324),
 (393, 0.0),
 (394, 0.022222222222222223),
 (395, 0.046004370622823615),
 (396, 0.03914801463431356),
 (397, 0.04714045207910317),
 (398, 0.0),
 (399, 0.020286020648339488),
 (400, 0.06984302957695783),
 (401, 0.026352313834736494),
 (402, 0.06523280730534423),
 (403, 0.07339758434175737),
 (404, 0.05443310539518174),
 (405, 0.04901430813958719),
 (406, 0.018633899812498248),
 (407, 0.019245008972987525),
 (408, 0.02923526731023431),
 (409, 0.0),
 (410, 0.08190601557786016),
 (411, 0.045466289298031565),
 (412, 0.0834965721446866),
 (413, 0.11640504929492972),
 (414, 0.0267739776300833),
 (415, 0.04714045207910317),
 (416, 0.044946657497549475),
 (417, 0.0298142396999972),
 (418, 0.030429030972509232),
 (419, 0.059761430466719695),
 (420, 0.0978700365857839),
 (421, 0.02087414303617165),
 (422, 0.10379985922153641),
 (423, 0.037267799624996496),
 (424, 0.03397647942917504),
 (425, 0.057259833431386825),
 (426, 0.04688072309384955),
 (427, 0.023570226039551584),
 (428, 0.04822428221704121),
 (429, 0.0),
 (430, 0.042591770999996),
 (431, 0.021516574145596764),
 (432, 0.10050378152592121),
 (433, 0.027681826617913324),
 (434, 0.0),
 (435, 0.030429030972509232),
 (436, 0.0),
 (437, 0.022473328748774737),
 (438, 0.10437071518085825),
 (439, 0.023570226039551584),
 (440, 0.021295885499998),
 (441, 0.04836508334066745),
 (442, 0.039840953644479794),
 (443, 0.05590169943749475),
 (444, 0.0),
 (445, 0.0879173964527716),
 (446, 0.02047650389446504),
 (447, 0.05822225097395821),
 (448, 0.018633899812498248),
 (449, 0.10079052613579392),
 (450, 0.018349396085439344),
 (451, 0.0219793491131929),
 (452, 0.02817180849095055),
 (453, 0.0219793491131929),
 (454, 0.1023825194723252),
 (455, 0.05590169943749475),
 (456, 0.038173222287591214),
 (457, 0.07669649888473704),
 (458, 0.034658349660669094),
 (459, 0.02923526731023431),
 (460, 0.022222222222222223),
 (461, 0.12253577034896798),
 (462, 0.02855686245854129),
 (463, 0.0267739776300833),
 (464, 0.0),
 (465, 0.0),
 (466, 0.13012000972647111),
 (467, 0.09390602830316849),
 (468, 0.023570226039551584),
 (469, 0.052342392259021375),
 (470, 0.04095300778893008),
 (471, 0.057735026918962574),
 (472, 0.09312403943594377),
 (473, 0.08268982305947231),
 (474, 0.0),
 (475, 0.057259833431386825),
 (476, 0.1147550621098494),
 (477, 0.0),
 (478, 0.049386479832479485),
 (479, 0.07991055024756402),
 (480, 0.08697707640712563),
 (481, 0.0),
 (482, 0.019086611143795607),
 (483, 0.1126872339638022),
 (484, 0.02556549962824568),
 (485, 0.04714045207910317),
 (486, 0.07172191381865588),
 (487, 0.1126872339638022),
 (488, 0.05933255459866464),
 (489, 0.0),
 (490, 0.12433397443204185),
 (491, 0.081813448945636),
 (492, 0.06900655593423542),
 (493, 0.028046877460778084),
 (494, 0.0),
 (495, 0.17541160386140586),
 (496, 0.0),
 (497, 0.0),
 (498, 0.0573775310549247),
 (499, 0.0),
 (500, 0.023281009858985943),
 (501, 0.07231015260621873),
 (502, 0.11952286093343938),
 (503, 0.0659380473395787),
 (504, 0.0),
 (505, 0.1192569587999888),
 (506, 0.03178208630818641),
 (507, 0.22360679774997896),
 (508, 0.08989331499509895),
 (509, 0.019744962591969745),
 (510, 0.08888888888888889),
 (511, 0.08451542547285165),
 (512, 0.023570226039551584),
 (513, 0.13483997249264842),
 (514, 0.04095300778893008),
 (515, 0.021744269101781406),
 (516, 0.022222222222222223),
 (517, 0.0),
 (518, 0.03948992518393949),
 (519, 0.0),
 (520, 0.0),
 (521, 0.020100756305184243),
 (522, 0.0219793491131929),
 (523, 0.0417482860723433),
 (524, 0.0),
 (525, 0.041344911529736156),
 (526, 0.024507154069793594),
 (527, 0.02868876552746235),
 (528, 0.01957400731715678),
 (529, 0.14333552726125529),
 (530, 0.049690399499995326),
 (531, 0.04020151261036849),
 (532, 0.018349396085439344),
 (533, 0.05536365323582665),
 (534, 0.0769800358919501),
 (535, 0.085183541999992),
 (536, 0.10050378152592121),
 (537, 0.0596284793999944),
 (538, 0.0),
 (539, 0.23008949665421108),
 (540, 0.0659380473395787),
 (541, 0.09466030570784414),
 (542, 0.03142696805273545),
 (543, 0.06262242910851495),
 (544, 0.04836508334066745),
 (545, 0.021744269101781406),
 (546, 0.05847053462046862),
 (547, 0.07071067811865475),
 (548, 0.0),
 (549, 0.10872134550890702),
 (550, 0.021744269101781406),
 (551, 0.03397647942917504),
 (552, 0.0),
 (553, 0.026352313834736494),
 (554, 0.0),
 (555, 0.03922322702763681),
 (556, 0.022733144649015782),
 (557, 0.10336227882434039),
 (558, 0.0),
 (559, 0.0267739776300833),
 (560, 0.03108349360801046),
 (561, 0.02817180849095055),
 (562, 0.02721655269759087),
 (563, 0.021744269101781406),
 (564, 0.0803219328902499),
 (565, 0.035634832254989916),
 (566, 0.02047650389446504),
 (567, 0.021516574145596764),
 (568, 0.12253577034896795),
 (569, 0.040572041296678976),
 (570, 0.060858061945018464),
 (571, 0.036155076303109365),
 (572, 0.09466030570784414),
 (573, 0.018633899812498248),
 (574, 0.02047650389446504),
 (575, 0.04095300778893008),
 (576, 0.04774099160262886),
 (577, 0.16709347060920102),
 (578, 0.050636968354183326),
 (579, 0.12598815766974242),
 (580, 0.0219793491131929),
 (581, 0.13176156917368248),
 (582, 0.21912524504463887),
 (583, 0.03397647942917504),
 (584, 0.06839855680567694),
 (585, 0.021516574145596764),
 (586, 0.03948992518393949),
 (587, 0.08432740427115679),
 (588, 0.023570226039551584),
 (589, 0.10614897848685505),
 (590, 0.02721655269759087),
 (591, 0.057259833431386825),
 (592, 0.0187812056606337),
 (593, 0.0),
 (594, 0.044444444444444446),
 (595, 0.14611900125320157),
 (596, 0.08114408259335795),
 (597, 0.04714045207910317),
 (598, 0.03178208630818641),
 (599, 0.023718935565494),
 (600, 0.062017367294604234),
 (601, 0.028822513411141126),
 (602, 0.08190601557786016),
 (603, 0.04714045207910317),
 (604, 0.0573775310549247),
 (605, 0.022473328748774737),
 (606, 0.0),
 (607, 0.051298917604257706),
 (608, 0.0),
 (609, 0.04095300778893008),
 (610, 0.05270462766947299),
 (611, 0.02047650389446504),
 (612, 0.05679618342470649),
 (613, 0.03178208630818641),
 (614, 0.04303314829119353),
 (615, 0.0563436169819011),
 (616, 0.027681826617913324),
 (617, 0.044444444444444446),
 (618, 0.07339758434175737),
 (619, 0.0),
 (620, 0.0),
 (621, 0.05536365323582665),
 (622, 0.01893206114156883),
 (623, 0.0),
 (624, 0.08770580193070293),
 (625, 0.0267739776300833),
 (626, 0.0716114874039433),
 (627, 0.09534625892455922),
 (628, 0.0),
 (629, 0.04348853820356281),
 (630, 0.021744269101781406),
 (631, 0.0375624113212674),
 (632, 0.06819943394704735),
 (633, 0.019920476822239897),
 (634, 0.0879173964527716),
 (635, 0.058722021951470346),
 (636, 0.02087414303617165),
 (637, 0.0219793491131929),
 (638, 0.030429030972509232),
 (639, 0.0),
 (640, 0.054635836470815304),
 (641, 0.0),
 (642, 0.0),
 (643, 0.08606629658238706),
 (644, 0.04348853820356281),
 (645, 0.038173222287591214),
 (646, 0.046562019717971886),
 (647, 0.04216370213557839),
 (648, 0.02721655269759087),
 (649, 0.0),
 (650, 0.045466289298031565),
 (651, 0.0),
 (652, 0.033757978902788886),
 (653, 0.09534625892455922),
 (654, 0.09390602830316849),
 (655, 0.021081851067789197),
 (656, 0.0),
 (657, 0.02996443833169965),
 (658, 0.042591770999996),
 (659, 0.021744269101781406),
 (660, 0.08451542547285165),
 (661, 0.15145648913255064),
 (662, 0.0),
 (663, 0.0),
 (664, 0.05270462766947299),
 (665, 0.062017367294604234),
 (666, 0.046004370622823615),
 (667, 0.0),
 (668, 0.1147550621098494),
 (669, 0.03178208630818641),
 (670, 0.015801515437999243),
 (671, 0.06030226891555273),
 (672, 0.02387049580131443),
 (673, 0.017946063401938852),
 (674, 0.06388765649999399),
 (675, 0.03914801463431356),
 (676, 0.021295885499998),
 (677, 0.0219793491131929),
 (678, 0.1070959105203332),
 (679, 0.0),
 (680, 0.06666666666666667),
 (681, 0.02387049580131443),
 (682, 0.018211945490271768),
 (683, 0.04348853820356281),
 (684, 0.0),
 (685, 0.02868876552746235),
 (686, 0.02721655269759087),
 (687, 0.09428090415820634),
 (688, 0.038814833982638804),
 (689, 0.0),
 (690, 0.021295885499998),
 (691, 0.05113099925649136),
 (692, 0.09872481295984872),
 (693, 0.03108349360801046),
 (694, 0.0187812056606337),
 (695, 0.0563436169819011),
 (696, 0.018633899812498248),
 (697, 0.0),
 (698, 0.03914801463431356),
 (699, 0.03178208630818641),
 (700, 0.025949964805384102),
 (701, 0.04901430813958719),
 (702, 0.019920476822239897),
 (703, 0.018349396085439344),
 (704, 0.06030226891555273),
 (705, 0.021295885499998),
 (706, 0.019407416991319402),
 (707, 0.0),
 (708, 0.022222222222222223),
 (709, 0.017817416127494958),
 (710, 0.052342392259021375),
 (711, 0.046004370622823615),
 (712, 0.0),
 (713, 0.022222222222222223),
 (714, 0.0),
 (715, 0.08606629658238704),
 (716, 0.02387049580131443),
 (717, 0.0),
 (718, 0.0375624113212674),
 (719, 0.0),
 (720, 0.023281009858985943),
 (721, 0.02721655269759087),
 (722, 0.0),
 (723, 0.021516574145596764),
 (724, 0.021744269101781406),
 (725, 0.0),
 (726, 0.0),
 (727, 0.027923593886113037),
 (728, 0.06324555320336758),
 (729, 0.0439586982263858),
 (730, 0.027446232319753947),
 (731, 0.04714045207910317),
 (732, 0.061429511683395124),
 (733, 0.055048188256318034),
 (734, 0.059761430466719695),
 (735, 0.05547001962252292),
 (736, 0.02556549962824568),
 (737, 0.06900655593423542),
 (738, 0.0),
 (739, 0.03419927840283847),

In [86]:
sorted_similarity = sorted(list(enumerate(similarity[0])), key=lambda x: x[1], reverse=True)
print(sorted_similarity)

[(0, 0.9999999999999999), (2405, 0.2504897164340598), (1214, 0.24845199749997662), (3728, 0.23333333333333334), (539, 0.23008949665421108), (507, 0.22360679774997896), (582, 0.21912524504463887), (1202, 0.21081851067789198), (778, 0.20874143036171655), (4046, 0.2038588765750502), (1192, 0.20082135869223647), (61, 0.19720265943665385), (1916, 0.191662969499982), (322, 0.18856180831641267), (3606, 0.18490006540840975), (74, 0.18428853505018536), (2329, 0.18428853505018536), (1087, 0.18333333333333332), (2782, 0.18164975363768873), (151, 0.17888543819998318), (4190, 0.17888543819998318), (47, 0.1769149641447584), (260, 0.17638342073763938), (3671, 0.1758347929055432), (495, 0.17541160386140586), (2969, 0.17447464086340458), (942, 0.17395415281425125), (972, 0.17391639824998364), (4405, 0.1721325931647741), (172, 0.17213259316477408), (305, 0.17177950029416045), (4, 0.16865480854231357), (577, 0.16709347060920102), (973, 0.167093470609201), (1199, 0.16609095970747995), (94, 0.16329931618554522), (1327, 0.16329931618554522), (27, 0.16269784336399215), (2997, 0.16265001215808889), (3325, 0.16265001215808889), (83, 0.16228816518671588), (3997, 0.1606438657804998), (1069, 0.1591320125431105), (220, 0.15811388300841897), (1273, 0.15811388300841897), (168, 0.15555555555555556), (184, 0.15555555555555556), (1342, 0.15555555555555556), (373, 0.1554174680400523), (1319, 0.1554174680400523), (1440, 0.1554174680400523), (36, 0.15385544379235033), (4336, 0.1538554437923503), (931, 0.15339299776947407), (2200, 0.15220988371246985), (3536, 0.15220988371246985), (661, 0.15145648913255064), (1353, 0.15061601901917734), (1827, 0.15061601901917734), (300, 0.14757295747452437), (91, 0.14704292441876157), (342, 0.14638501094228), (41, 0.14611900125320157), (595, 0.14611900125320157), (838, 0.14383899044561524), (2727, 0.14344382763731175), (529, 0.14333552726125529), (150, 0.14301938838683884), (3160, 0.14253932901995967), (67, 0.1414213562373095), (1533, 0.1407052941362897), (4008, 0.1405456737852613), (1176, 0.13968605915391566), (1978, 0.13968605915391566), (149, 0.13957971269072367), (31, 0.13840913308956662), (26, 0.1363988678940947), (2071, 0.13608276348795434), (2511, 0.13608276348795434), (187, 0.13483997249264842), (513, 0.13483997249264842), (52, 0.13333333333333333), (111, 0.13333333333333333), (2756, 0.13252442799098182), (1379, 0.13187609467915742), (581, 0.13176156917368248), (127, 0.13169727955327862), (7, 0.13046561461068845), (108, 0.13046561461068845), (311, 0.13046561461068845), (466, 0.13012000972647111), (275, 0.1297498240269205), (294, 0.1297498240269205), (1054, 0.12909944487358058), (2492, 0.1278274981412284), (1295, 0.12777531299998798), (1934, 0.12777531299998798), (1484, 0.12712834523274563), (3779, 0.12712834523274563), (1392, 0.12654276706088277), (46, 0.12598815766974242), (579, 0.12598815766974242), (2165, 0.12598815766974242), (490, 0.12433397443204185), (1325, 0.12433397443204185), (3352, 0.12422599874998831), (1475, 0.12297746456210365), (17, 0.12297746456210364), (1961, 0.12297746456210364), (4538, 0.12285902336679025), (461, 0.12253577034896798), (859, 0.12253577034896797), (568, 0.12253577034896795), (56, 0.12171612389003693), (3980, 0.12171612389003693), (777, 0.12171612389003691), (843, 0.12091270835166862), (4077, 0.12091270835166862), (4348, 0.11952286093343939), (502, 0.11952286093343938), (72, 0.11935247900657214), (1556, 0.11935247900657214), (505, 0.1192569587999888), (2580, 0.1192569587999888), (95, 0.11846977555181848), (1271, 0.11846977555181848), (2129, 0.11846977555181847), (249, 0.11694106924093724), (773, 0.11694106924093724), (2869, 0.1164445019479164), (14, 0.11640504929492972), (138, 0.11640504929492972), (413, 0.11640504929492972), (2682, 0.11640504929492972), (3620, 0.11640504929492972), (1320, 0.1159442654999891), (2446, 0.11501092655705904), (3626, 0.11501092655705904), (476, 0.1147550621098494), (668, 0.1147550621098494), (2374, 0.1147550621098494), (1013, 0.11366572324507891), (1084, 0.11366572324507891), (4228, 0.11366572324507891), (134, 0.1126872339638022), (483, 0.1126872339638022), (487, 0.1126872339638022), (935, 0.1126872339638022), (754, 0.11236664374387369), (1804, 0.11236664374387369), (2177, 0.11236664374387369), (2670, 0.1118033988749895), (3081, 0.1118033988749895), (158, 0.11180339887498948), (68, 0.1107273064716533), (368, 0.1107273064716533), (1156, 0.1107273064716533), (1369, 0.1107273064716533), (1770, 0.1107273064716533), (126, 0.10989674556596452), (102, 0.10927167294163062), (1737, 0.10927167294163062), (208, 0.10886621079036347), (1002, 0.10886621079036347), (1829, 0.10886621079036347), (369, 0.10872134550890704), (549, 0.10872134550890702), (1297, 0.10872134550890702), (1669, 0.1084652289093281), (1711, 0.1084652289093281), (2476, 0.1084652289093281), (2785, 0.1084652289093281), (678, 0.1070959105203332), (1045, 0.1070959105203332), (1094, 0.1070959105203332), (1272, 0.1070959105203332), (1654, 0.1070959105203332), (160, 0.10650160840378231), (166, 0.10647942749999), (900, 0.10647942749999), (1613, 0.10647942749999), (3233, 0.10647942749998998), (589, 0.10614897848685505), (937, 0.10540925533894599), (2280, 0.10540925533894599), (1000, 0.10540925533894598), (2968, 0.10540925533894598), (3374, 0.10540925533894598), (3734, 0.10540925533894598), (438, 0.10437071518085825), (3407, 0.10437071518085825), (85, 0.10434983894999018), (84, 0.10397504898200727), (122, 0.10379985922153641), (422, 0.10379985922153641), (2648, 0.10379985922153641), (2737, 0.10379985922153641), (4673, 0.10379985922153641), (781, 0.1037998592215364), (557, 0.10336227882434039), (1414, 0.10336227882434039), (139, 0.10327955589886444), (1493, 0.10327955589886444), (1874, 0.10259783520851543), (3210, 0.1025978352085154), (278, 0.1023825194723252), (454, 0.1023825194723252), (2056, 0.10226199851298272), (889, 0.10183501544346313), (870, 0.10143010324169743), (232, 0.10079052613579392), (449, 0.10079052613579392), (3145, 0.10063092108532554), (432, 0.10050378152592121), (536, 0.10050378152592121), (1218, 0.10050378152592121), (189, 0.1), (1570, 0.1), (2327, 0.1), (3719, 0.1), (238, 0.09999999999999999), (43, 0.09960238411119948), (2543, 0.09960238411119948), (236, 0.09938079899999065), (4468, 0.09938079899999065), (123, 0.09872481295984872), (182, 0.09872481295984872), (228, 0.09872481295984872), (692, 0.09872481295984872), (2368, 0.09872481295984872), (3307, 0.09872481295984872), (3628, 0.09872481295984872), (206, 0.09860132971832693), (28, 0.09802861627917438), (1612, 0.09802861627917438), (3496, 0.09802861627917438), (420, 0.0978700365857839), (1346, 0.09759000729485334), (4133, 0.09759000729485334), (1508, 0.09703708495659702), (87, 0.0967301666813349), (786, 0.0967301666813349), (3006, 0.0967301666813349), (3426, 0.0967301666813349), (5, 0.09622504486493763), (740, 0.09622504486493763), (3091, 0.09622504486493763), (21, 0.09548198320525772), (295, 0.09548198320525772), (1235, 0.09548198320525772), (170, 0.09543305571897803), (627, 0.09534625892455922), (653, 0.09534625892455922), (808, 0.09534625892455922), (1497, 0.09534625892455922), (1520, 0.09534625892455922), (1571, 0.09534625892455922), (2630, 0.09534625892455922), (3053, 0.09534625892455922), (307, 0.09486348995453654), (541, 0.09466030570784414), (572, 0.09466030570784414), (229, 0.09428090415820635), (50, 0.09428090415820634), (131, 0.09428090415820634), (687, 0.09428090415820634), (1029, 0.09428090415820634), (3632, 0.09428090415820634), (262, 0.09390602830316849), (467, 0.09390602830316849), (654, 0.09390602830316849), (2102, 0.09390602830316849), (939, 0.09376144618769909), (256, 0.09325048082403138), (1164, 0.09325048082403138), (1741, 0.09325048082403138), (3998, 0.09325048082403138), (1451, 0.09316949906249124), (121, 0.09312403943594377), (332, 0.09312403943594377), (472, 0.09312403943594377), (1492, 0.09245003270420486), (2494, 0.09245003270420486), (75, 0.09200874124564723), (174, 0.09200874124564723), (223, 0.09200874124564723), (775, 0.09200874124564723), (2813, 0.09200874124564723), (200, 0.09128709291752769), (319, 0.09128709291752769), (2157, 0.09128709291752769), (2319, 0.09128709291752769), (2517, 0.09128709291752769), (2758, 0.09128709291752769), (3619, 0.09128709291752769), (3659, 0.09128709291752769), (4490, 0.09128709291752769), (1941, 0.09093257859606313), (3338, 0.09093257859606313), (1435, 0.09038769075777342), (266, 0.08989331499509895), (330, 0.08989331499509895), (508, 0.08989331499509895), (1292, 0.08989331499509895), (2243, 0.08989331499509895), (3150, 0.08989331499509895), (3753, 0.08989331499509895), (4095, 0.08989331499509895), (4777, 0.08989331499509895), (1401, 0.08973031700969426), (2435, 0.08973031700969426), (105, 0.0894427190999916), (233, 0.0894427190999916), (1075, 0.0894427190999916), (1278, 0.0894427190999916), (3837, 0.0894427190999916), (4472, 0.0894427190999916), (363, 0.0890870806374748), (510, 0.08888888888888889), (1035, 0.08888888888888889), (1288, 0.08888888888888889), (1610, 0.08888888888888889), (1819, 0.08888888888888889), (2249, 0.08888888888888889), (81, 0.08856148855400954), (1771, 0.0884574820723792), (2095, 0.0884574820723792), (312, 0.0879173964527716), (445, 0.0879173964527716), (634, 0.0879173964527716), (2144, 0.0879173964527716), (35, 0.08770580193070293), (624, 0.08770580193070293), (3952, 0.08770580193070293), (9, 0.08697707640712563), (10, 0.08697707640712563), (207, 0.08697707640712563), (480, 0.08697707640712563), (986, 0.08697707640712563), (1107, 0.08697707640712563), (1193, 0.08697707640712563), (1767, 0.08697707640712563), (2068, 0.08697707640712563), (2237, 0.08697707640712563), (18, 0.08664587415167274), (4545, 0.08664587415167274), (371, 0.08606629658238706), (643, 0.08606629658238706), (898, 0.08606629658238706), (1397, 0.08606629658238706), (2391, 0.08606629658238706), (3718, 0.08606629658238706), (3872, 0.08606629658238706), (3933, 0.08606629658238706), (33, 0.08606629658238704), (157, 0.08606629658238704), (362, 0.08606629658238704), (715, 0.08606629658238704), (791, 0.08606629658238704), (1682, 0.08606629658238704), (1938, 0.08606629658238704), (2049, 0.08606629658238704), (2452, 0.08606629658238704), (2783, 0.08606629658238704), (4016, 0.08606629658238704), (4254, 0.08606629658238704), (3439, 0.08606629658238701), (535, 0.085183541999992), (2588, 0.085183541999992), (2816, 0.085183541999992), (263, 0.08451542547285165), (511, 0.08451542547285165), (660, 0.08451542547285165), (1154, 0.08451542547285165), (1717, 0.08451542547285165), (1723, 0.08451542547285165), (2558, 0.08451542547285165), (2641, 0.08451542547285165), (3535, 0.08451542547285165), (4331, 0.08451542547285165), (4403, 0.08451542547285165), (334, 0.08432740427115679), (587, 0.08432740427115679), (1080, 0.08432740427115679), (1299, 0.08432740427115679), (1688, 0.08432740427115679), (2484, 0.08432740427115679), (2552, 0.08432740427115679), (3618, 0.08432740427115679), (11, 0.0834965721446866), (412, 0.0834965721446866), (1697, 0.0834965721446866), (1992, 0.0834965721446866), (239, 0.08333333333333334), (88, 0.08304547985373997), (325, 0.08304547985373997), (920, 0.08304547985373997), (1476, 0.08304547985373997), (4196, 0.08304547985373997), (301, 0.08281733249999221), (799, 0.08281733249999221), (473, 0.08268982305947231), (814, 0.08268982305947231), (1231, 0.08268982305947231), (1274, 0.08268982305947231), (1842, 0.08268982305947231), (4353, 0.08268982305947231), (785, 0.08231079972079913), (410, 0.08190601557786016), (602, 0.08190601557786016), (813, 0.08190601557786016), (1355, 0.08190601557786016), (1442, 0.08190601557786016), (2646, 0.08190601557786016), (3387, 0.08190601557786016), (3879, 0.08190601557786016), (491, 0.081813448945636), (2566, 0.081813448945636), (148, 0.08164965809277261), (219, 0.08164965809277261), (244, 0.08164965809277261), (356, 0.08164965809277261), (878, 0.08164965809277261), (978, 0.08164965809277261), (1569, 0.08164965809277261), (1752, 0.08164965809277261), (3320, 0.08164965809277261), (230, 0.08132500607904444), (596, 0.08114408259335795), (3781, 0.08114408259335795), (243, 0.08040302522073697), (270, 0.08040302522073697), (279, 0.08040302522073697), (1902, 0.08040302522073697), (389, 0.0803219328902499), (564, 0.0803219328902499), (1880, 0.0803219328902499), (2089, 0.0803219328902499), (2247, 0.0803219328902499), (4201, 0.0803219328902499), (479, 0.07991055024756402), (2111, 0.07991055024756402), (995, 0.07968190728895959), (2709, 0.07968190728895959), (3460, 0.07968190728895959), (4516, 0.07968190728895959), (141, 0.07905694150420949), (167, 0.07905694150420949), (292, 0.07905694150420949), (1025, 0.07905694150420949), (1257, 0.07905694150420949), (1304, 0.07905694150420949), (2647, 0.07905694150420949), (2656, 0.07905694150420949), (2864, 0.07905694150420949), (3133, 0.07905694150420949), (3447, 0.07905694150420949), (2105, 0.07897985036787898), (4343, 0.07897985036787898), (752, 0.07829602926862712), (1017, 0.07829602926862712), (2736, 0.07829602926862712), (3441, 0.07829602926862712), (3551, 0.07829602926862712), (3554, 0.07829602926862712), (2, 0.07784989441615231), (23, 0.07784989441615231), (960, 0.07784989441615231), (1140, 0.07784989441615231), (1247, 0.07784989441615231), (1470, 0.07784989441615231), (2392, 0.07784989441615231), (2955, 0.07784989441615231), (1828, 0.07762966796527761), (2444, 0.07728981596002804), (32, 0.0769800358919501), (169, 0.0769800358919501), (217, 0.0769800358919501), (234, 0.0769800358919501), (331, 0.0769800358919501), (534, 0.0769800358919501), (827, 0.0769800358919501), (2852, 0.0769800358919501), (2876, 0.0769800358919501), (3178, 0.0769800358919501), (3976, 0.0769800358919501), (4502, 0.0769800358919501), (4587, 0.0769800358919501), (4737, 0.0769800358919501), (457, 0.07669649888473704), (894, 0.07669649888473704), (1374, 0.07669649888473704), (2300, 0.07669649888473704), (3446, 0.07669649888473704), (4754, 0.07669649888473704), (48, 0.07634644457518243), (1303, 0.07634644457518243), (2359, 0.07634644457518243), (3405, 0.07634644457518243), (143, 0.07572824456627532), (199, 0.07572824456627532), (1635, 0.07572824456627532), (1095, 0.07559289460184546), (745, 0.07559289460184544), (2657, 0.07559289460184544), (274, 0.07511265766429255), (12, 0.07453559924999299), (152, 0.07453559924999299), (315, 0.07453559924999299), (812, 0.07453559924999299), (1526, 0.07453559924999299), (1660, 0.07453559924999299), (1694, 0.07453559924999299), (1745, 0.07453559924999299), (2873, 0.07453559924999299), (3138, 0.07453559924999299), (3216, 0.07453559924999299), (3525, 0.07453559924999299), (4560, 0.07453559924999299), (4641, 0.07453559924999299), (4654, 0.07453559924999299), (4657, 0.07453559924999299), (1200, 0.07396002616336389), (2966, 0.07396002616336389), (1, 0.07352146220938079), (1205, 0.07352146220938079), (1267, 0.07352146220938079), (1515, 0.07352146220938079), (1585, 0.07352146220938079), (3299, 0.07352146220938079), (3814, 0.07352146220938079), (129, 0.07339758434175737), (403, 0.07339758434175737), (618, 0.07339758434175737), (1779, 0.07339758434175737), (2199, 0.07339758434175737), (2350, 0.07339758434175737), (3903, 0.07339758434175737), (19, 0.07284778196108707), (45, 0.07284778196108707), (1894, 0.07284778196108707), (37, 0.07254762501100118), (227, 0.07254762501100118), (1078, 0.07254762501100118), (2124, 0.07254762501100118), (2679, 0.07254762501100118), (3924, 0.07254762501100118), (62, 0.07231015260621873), (63, 0.07231015260621873), (381, 0.07231015260621873), (501, 0.07231015260621873), (776, 0.07231015260621873), (2335, 0.07231015260621873), (2792, 0.07231015260621873), (193, 0.07172191381865588), (486, 0.07172191381865588), (2382, 0.07172191381865588), (142, 0.0716114874039433), (626, 0.0716114874039433), (1147, 0.0716114874039433), (1743, 0.0716114874039433), (2861, 0.0716114874039433), (3026, 0.0716114874039433), (3100, 0.0716114874039433), (3231, 0.0716114874039433), (3468, 0.0716114874039433), (4626, 0.0716114874039433), (1530, 0.07126966450997983), (153, 0.07076598565790336), (3558, 0.07076598565790336), (16, 0.07071067811865475), (245, 0.07071067811865475), (306, 0.07071067811865475), (547, 0.07071067811865475), (2579, 0.07071067811865475), (2936, 0.07071067811865475), (38, 0.07027283689263066), (866, 0.07027283689263066), (1922, 0.07027283689263066), (2270, 0.07027283689263066), (4279, 0.07027283689263066), (4492, 0.07027283689263066), (39, 0.06984302957695783), (112, 0.06984302957695783), (203, 0.06984302957695783), (329, 0.06984302957695783), (400, 0.06984302957695783), (787, 0.06984302957695783), (901, 0.06984302957695783), (922, 0.06984302957695783), (1159, 0.06984302957695783), (1323, 0.06984302957695783), (2215, 0.06984302957695783), (2640, 0.06984302957695783), (4316, 0.06984302957695783), (4341, 0.06984302957695783), (4624, 0.06984302957695783), (103, 0.06978985634536183), (222, 0.06978985634536183), (246, 0.06978985634536183), (2788, 0.06978985634536183), (4506, 0.06978985634536183), (1824, 0.06931669932133819), (125, 0.06921285402059828), (40, 0.06900655593423542), (70, 0.06900655593423542), (492, 0.06900655593423542), (737, 0.06900655593423542), (1291, 0.06900655593423542), (3849, 0.06900655593423542), (4558, 0.06900655593423542), (286, 0.06885303726590962), (1655, 0.06885303726590962), (1920, 0.06885303726590962), (584, 0.06839855680567694), (1280, 0.06839855680567694), (3115, 0.06839855680567694), (3124, 0.06839855680567694), (3726, 0.06839855680567694), (3830, 0.06839855680567694), (4473, 0.06839855680567694), (4568, 0.06839855680567694), (3329, 0.06832667180756564), (164, 0.06819943394704735), (241, 0.06819943394704735), (242, 0.06819943394704735), (349, 0.06819943394704735), (632, 0.06819943394704735), (794, 0.06819943394704735), (854, 0.06819943394704735), (899, 0.06819943394704735), (1068, 0.06819943394704735), (1111, 0.06819943394704735), (1287, 0.06819943394704735), (2291, 0.06819943394704735), (2445, 0.06819943394704735), (3089, 0.06819943394704735), (3162, 0.06819943394704735), (4266, 0.06819943394704735), (1986, 0.06751595780557777), (101, 0.06741998624632421), (210, 0.06741998624632421), (361, 0.06741998624632421), (1519, 0.06741998624632421), (98, 0.06666666666666667), (235, 0.06666666666666667), (365, 0.06666666666666667), (680, 0.06666666666666667), (850, 0.06666666666666667), (1003, 0.06666666666666667), (1321, 0.06666666666666667), (1363, 0.06666666666666667), (1517, 0.06666666666666667), (1651, 0.06666666666666667), (1766, 0.06666666666666667), (2052, 0.06666666666666667), (2708, 0.06666666666666667), (3067, 0.06666666666666667), (3070, 0.06666666666666667), (3153, 0.06666666666666667), (3714, 0.06666666666666667), (3762, 0.06666666666666667), (3803, 0.06666666666666667), (4163, 0.06666666666666667), (4431, 0.06666666666666667), (790, 0.06625386599999376), (2252, 0.06625386599999376), (71, 0.0659380473395787), (82, 0.0659380473395787), (96, 0.0659380473395787), (341, 0.0659380473395787), (503, 0.0659380473395787), (540, 0.0659380473395787), (1007, 0.0659380473395787), (1619, 0.0659380473395787), (1684, 0.0659380473395787), (2159, 0.0659380473395787), (2986, 0.0659380473395787), (190, 0.06584863977663931), (1483, 0.0654507591565088), (402, 0.06523280730534423), (2914, 0.06523280730534423), (3353, 0.06523280730534423), (3421, 0.06523280730534423), (3699, 0.06523280730534423), (4203, 0.06523280730534423), (51, 0.06506000486323556), (1137, 0.06506000486323556), (1252, 0.06506000486323556), (1485, 0.06506000486323556), (1617, 0.06506000486323556), (1955, 0.06506000486323556), (2322, 0.06506000486323556), (2377, 0.06506000486323556), (2475, 0.06506000486323556), (2667, 0.06506000486323556), (2797, 0.06506000486323556), (3974, 0.06506000486323556), (4009, 0.06506000486323556), (4542, 0.06506000486323556), (4638, 0.06506000486323556), (2001, 0.06467616667635546), (3429, 0.06467616667635546), (977, 0.06454972243679029), (1143, 0.06454972243679029), (3020, 0.06454972243679029), (3609, 0.06454972243679029), (59, 0.06429904295605494), (2186, 0.06392844019805122), (86, 0.0638876564999

In [87]:
def recommend(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [91]:
recommend('Shutter Island')

The Good German
Gone Girl
10th & Wolf
Interview with the Assassin
Dragonfly

In [89]:
# Save the processed movie data (new) and the similarity matrix (similarity) into pickle files for future use or model deployment.
import pickle
pickle.dump(new,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))